In [1]:

from dotenv import load_dotenv
import os
import pandas as pd
import sqlalchemy

pd.set_option('display.max_columns', None)
load_dotenv()


sqlalchemy.create_engine(os.environ["DATABASE_URL"])

%load_ext sql

print(" inline sql successfully connected")

 inline sql successfully connected

In [2]:
%%sql
select *
from members
where "tenantId" = 'ccff5355-cf54-40a1-9a2e-8e4a447ae73a'
order by "joinedAt" desc
limit 10

10 rows affected.

[(UUID('d4dbbb76-7b42-4f28-9b89-8fbfd65088e4'), None, {'avatarUrl': {'default': 'https://avatars.githubusercontent.com/u/8527189?v=4'}}, 'Alois Mayr', ['alois.mayr@dynatrace.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 9, 668000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 9, 688000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 9, 688000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('f2a03057-6338-4c58-b632-78990258b0f3'), None, {}, 'Susobhit Panigrahi', ['susobhitp@vmware.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 8, 846000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 8, 866000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 8, 866000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('6516c12f-70cf-4fcb-922f-9aa5971c1eca'), None, {'avatarUrl': {'default': 'https://lfx-cdn-prod.s3.amazonaws.com/users/avatar/s.png'}}, 'Stephen Boyd', ['swboyd@google.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 7, 516000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 7, 536000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 7, 536000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('3126373f-a730-4dc1-9972-0bdecca8a3f6'), None, {}, 'Stefano Pirovano', ['stefano@diamanti.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 6, 807000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 6, 827000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 6, 827000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('518cf434-f657-4b0d-b37d-cd2be7123089'), None, {}, 'Oliver Johnston-Watt', ['oliver@blockchaintp.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 6, 99000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 6, 122000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 6, 122000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('89c812bb-867f-48a0-9773-8cadd5f42584'), None, {}, 'Michael Dielman', ['mdielman@twistlock.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 5, 350000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 5, 370000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 5, 370000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('cbb3e81e-b556-402b-ae5d-75abd408b6d0'), None, {}, 'Bakari SUMAILA', ['marion.courtet@jobteaser.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 4, 678000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 4, 698000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 4, 698000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('3e589986-9892-4973-8728-c9a2a6dc8f57'), None, {}, "Rachel O'Toole", ['rachel.o.toole@ericsson.com'], -1, datetime.datetime(2023, 5, 11, 0, 24, 4, 44000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 24, 4, 64000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 24, 4, 64000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('4b966ba7-ef47-48ca-9932-7cc6ea15bd79'), None, {}, 'Nisan Itzhakov', ['nisan.itzhakov@riskified.com'], -1, datetime.datetime(2023, 5, 11, 0, 2, 2, 807000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 2, 2, 824000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 2, 2, 824000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], []),
 (UUID('e866f151-044c-47b5-9c96-44073c367e63'), None, {}, 'Omer Kahani', ['omer@riskified.com'], -1, datetime.datetime(2023, 5, 11, 0, 2, 0, 875000, tzinfo=datetime.timezone.utc), None, {'total': -1}, datetime.datetime(2023, 5, 11, 0, 2, 0, 891000, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 5, 11, 0, 2, 0, 891000, tzinfo=datetime.timezone.utc), None, UUID('ccff5355-cf54-40a1-9a2e-8e4a447ae73a'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), UUID('431d79d5-2eb8-4d3b-ab3d-db2f6c0a3591'), None, None, [], [])]

In [3]:
%%sql
select 
activities."username", count(*) tt
from activities
where activities."tenantId"='ccff5355-cf54-40a1-9a2e-8e4a447ae73a'
and timestamp > current_date - interval '1days'
group by 1
order by 1
limit 100

*  postgresql://crowd:***@127.0.0.1:5000/crowd
3 rows affected.

[('nickmango', 9), ('thakurveerendras', 2), ('umeshlumbhani247', 1)]

# Metric Contributions 
a contribution is any activity set by as isContribution = true

In [5]:
%%sql
select 
members."attributes" -> 'avatarUrl' ->>'github' "logo_url",
activities."username",
count(*) activities_count
from activities
left join members on members.id = activities."memberId"
where activities."tenantId"='ccff5355-cf54-40a1-9a2e-8e4a447ae73a'
and "isContribution" = true
and timestamp > current_date - interval '7 days'
group by 1,2
order by activities_count desc

*  postgresql://crowd:***@127.0.0.1:5000/crowd
4 rows affected.

[('https://avatars.githubusercontent.com/u/81645226?v=4', 'nickmango', 12),
 ('https://avatars.githubusercontent.com/u/129035502?v=4', 'umeshlumbhani247', 9),
 ('https://avatars.githubusercontent.com/u/75417507?v=4', 'thakurveerendras', 9),
 ('https://avatars.githubusercontent.com/u/93140557?v=4', 'jarias-lfx', 2)]

## Metric Contributions: Pull request
1. Option 1: Count activities
Count activities in PR types , would be the count of contributions in PRs, so a user can have 1 or more contributions in the same PR

2. Option 2: Count PRs
Count PRs, would be the count of  PRs, so a user 1 contribution per PR

Option 1: is the simplest